In [1]:
import numpy as np

In [6]:
array_two = np.arange(0,4)**2
array_two

array([0, 1, 4, 9])

In [7]:
sample_arr =np.array([1,2,3])


In [8]:
np.exp(sample_arr)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [10]:
np.sin(sample_arr)

array([0.84147098, 0.90929743, 0.14112001])

In [11]:
np.negative(sample_arr)

array([-1, -2, -3])

In [12]:
np.power(sample_arr,4)

array([ 1, 16, 81])

In [14]:
# N dimension array
# 1 D - [1,]
# 2 D - [1,2]

In [15]:
x = np.arange(3) #[0,1,2]

In [16]:
x

array([0, 1, 2])

In [22]:
x = np.arange(3)
y = np.arange(3)
z = np.arange(3)

m_array = np.array([x,y,z])
m_array

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [23]:

m_array.shape

(3, 3)

In [27]:
w = np.linspace(1,10,3)
print(w)

[ 1.   5.5 10. ]


In [28]:
w = np.arange(1,10,3)
print(w)

[1 4 7]


In [29]:
w = np.linspace(1,10,30)
print(w)

[ 1.          1.31034483  1.62068966  1.93103448  2.24137931  2.55172414
  2.86206897  3.17241379  3.48275862  3.79310345  4.10344828  4.4137931
  4.72413793  5.03448276  5.34482759  5.65517241  5.96551724  6.27586207
  6.5862069   6.89655172  7.20689655  7.51724138  7.82758621  8.13793103
  8.44827586  8.75862069  9.06896552  9.37931034  9.68965517 10.        ]


In [31]:
w = np.linspace(1,10,30,False) # not include last digit 10
print(w)

[1.  1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4.  4.3 4.6 4.9 5.2 5.5 5.8 6.1
 6.4 6.7 7.  7.3 7.6 7.9 8.2 8.5 8.8 9.1 9.4 9.7]


In [34]:
x = np.arange(3)
y = np.arange(3,6)
z = np.arange(6,9)

m_array = np.array([x,y,z])
m_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
m_array[0,2]

2

In [37]:
print(m_array.dtype)

int64


In [38]:
x = np.arange(3)
y = np.arange(3,6)
z = np.arange(6,9)

m_array = np.array([x,y,z], dtype="int16")
m_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int16)

In [39]:
print(m_array.dtype)

int16


In [40]:
#Slicing

In [41]:
#Reshaping

In [42]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
x = np.arange(9).reshape(3,3) # 1 D to 3D
x 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
x = np.arange(9).reshape(3,-1)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
x = np.arange(18).reshape(3,3,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [50]:
 #nD-1D
 x.ravel()   
    

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [55]:
x.ravel()  
x[2] = 1000
x

array([[[   0,    1],
        [   2,    3],
        [   4,    5]],

       [[   6,    7],
        [   8,    9],
        [  10,   11]],

       [[1000, 1000],
        [1000, 1000],
        [1000, 1000]]])

In [48]:
 x.flatten() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [61]:
y = np.arange(9)
y.shape = [3,3]
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
y.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [63]:
y.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [64]:
np.resize(y,(6,6))

array([[0, 1, 2, 3, 4, 5],
       [6, 7, 8, 0, 1, 2],
       [3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5],
       [6, 7, 8, 0, 1, 2],
       [3, 4, 5, 6, 7, 8]])

In [66]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [67]:
np.zeros((6,6),dtype='int32')

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [68]:
np.ones((6,6),dtype='int32')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [69]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
np.random.rand(4,4)

array([[0.86758866, 0.14274068, 0.23160099, 0.60466244],
       [0.65076538, 0.17307437, 0.65501583, 0.22919038],
       [0.24763917, 0.51811831, 0.35987943, 0.14769603],
       [0.22898351, 0.67022033, 0.43438086, 0.13241764]])

In [72]:
# Matrix multiplication

In [74]:
mat_a = np.matrix([1,2,3,4,5,6]).reshape(2,3)
mat_a

matrix([[1, 2, 3],
        [4, 5, 6]])

In [78]:
mat_b = np.matrix([1,2,3,4,5,6]).reshape(3,2)
mat_b

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [79]:
mat_a * mat_b

matrix([[22, 28],
        [49, 64]])

In [82]:
mul = np.matmul(mat_a,mat_b)
mul

matrix([[22, 28],
        [49, 64]])

In [83]:
mat_a @ mat_b

matrix([[22, 28],
        [49, 64]])